/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.damdes;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.lang.NullPointerException;
import javax.swing.table.DefaultTableModel;
import com.mysql.cj.xdevapi.Table;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;



/**
 *
 * @author M FAKIH IZZUL HAQ
 */
public class SubBeranda_tagihan extends javax.swing.JFrame {
    private JPanel currentPanel;
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form SubBeranda_tagihan
     */
    public SubBeranda_tagihan() {
        initComponents();
        conn = DAMDES.connect();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }
    public void tampil_data() {
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID Number");
    tabel.addColumn("No Rumah");
    tabel.addColumn("Kode Bayar");
    tabel.addColumn("Bulan");
    tabel.addColumn("Tanggal");
    tabel.addColumn("Jenis Tagihan");

    try {
        java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();
        String sql = "SELECT * FROM subberanda_tagihan";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            tabel.addRow(new Object[]{
                rs.getString("id_number"),
                rs.getString("no_rumah"),
                rs.getString("kode_bayar"),
                rs.getString("bulan"),
                rs.getString("tanggal"),
                rs.getString("jenis_tagihan")
            });
        }
        jTable1.setModel(tabel);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_tampil = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_idnum = new javax.swing.JTextField();
        txt_kodebyr = new javax.swing.JTextField();
        txt_norumah1 = new javax.swing.JTextField();
        txt_tagihan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        txt_bulan = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Username.setBackground(new java.awt.Color(0, 232, 232));
        Username.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Selamat Datang di Aplikasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 52), new java.awt.Color(0, 0, 204))); // NOI18N
        Username.setForeground(new java.awt.Color(0, 51, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Desa Akses Mandiri");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Pengelola Pembayaran Sampah dari BUMDes");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nomor Rumah");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID Number      ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Kode Bayar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tanggal");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Jenis Tagihan");

        btn_tampil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tampil.setText("Tampil");
        btn_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tampilActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 30));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_search.setText("Cari");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel2.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID NUMBER", "NO RUMAH", "KODE BAYAR", "BULAN", "TANGGAL", "JENIS TAGIHAN"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 690, 330));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        txt_idnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idnumActionPerformed(evt);
            }
        });

        txt_kodebyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodebyrActionPerformed(evt);
            }
        });

        txt_norumah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_norumah1ActionPerformed(evt);
            }
        });

        txt_tagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tagihanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Bulan");

        txt_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalActionPerformed(evt);
            }
        });

        txt_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bulanActionPerformed(evt);
            }
        });

        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsernameLayout = new javax.swing.GroupLayout(Username);
        Username.setLayout(UsernameLayout);
        UsernameLayout.setHorizontalGroup(
            UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernameLayout.createSequentialGroup()
                .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsernameLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsernameLayout.createSequentialGroup()
                                .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(116, 116, 116))
                            .addGroup(UsernameLayout.createSequentialGroup()
                                .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UsernameLayout.createSequentialGroup()
                                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(btn_tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(UsernameLayout.createSequentialGroup()
                                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_kodebyr)
                                .addComponent(txt_norumah1)
                                .addComponent(txt_tagihan)
                                .addComponent(txt_tanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_bulan))
                            .addComponent(txt_idnum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UsernameLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsernameLayout.setVerticalGroup(
            UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernameLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsernameLayout.createSequentialGroup()
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txt_idnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_norumah1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_kodebyr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_bulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_tanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_tagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_tampil)
                            .addComponent(btn_edit)
                            .addComponent(btn_hapus))
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kodebyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodebyrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodebyrActionPerformed

    private void txt_norumah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_norumah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_norumah1ActionPerformed

    private void txt_tagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tagihanActionPerformed

    private void txt_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalActionPerformed

    private void txt_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bulanActionPerformed

    private void btn_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tampilActionPerformed
        // TODO add your handling code here:
        tampil_data();
    }//GEN-LAST:event_btn_tampilActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
    String id_number = txt_idnum.getText();
    String no_rumah = txt_norumah1.getText();
    String kode_bayar = txt_kodebyr.getText();
    String bulan = txt_bulan.getText();
    String tanggal = txt_tanggal.getText();
    String jenis_tagihan = txt_tagihan.getText();

    // Periksa apakah ada input yang kosong
    if (id_number.isEmpty() || no_rumah.isEmpty() || kode_bayar.isEmpty() || bulan.isEmpty() || tanggal.isEmpty() || jenis_tagihan.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Masukkan semua data tagihan.");
        return;
    }

    // Buat query SQL untuk memperbarui data dengan parameter
    String sqlquery = "UPDATE subberanda_tagihan SET no_rumah = ?, kode_bayar = ?, bulan = ?, tanggal = ?, jenis_tagihan = ? WHERE id_number = ?";

    try {
        // Mendapatkan koneksi ke database
        java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();

        // Menggunakan PreparedStatement untuk membuat query dengan parameter
        java.sql.PreparedStatement pst = conn.prepareStatement(sqlquery);
        
        // Set parameter PreparedStatement
        pst.setString(1, no_rumah);
        pst.setString(2, kode_bayar);
        pst.setString(3, bulan);
        pst.setString(4, tanggal);
        pst.setString(5, jenis_tagihan);
        pst.setString(6, id_number);

        // Eksekusi query
        pst.executeUpdate();

        // Reset teks input setelah berhasil
        txt_idnum.setText("");
        txt_norumah1.setText("");
        txt_kodebyr.setText("");
        txt_bulan.setText("");
        txt_tanggal.setText("");
        txt_tagihan.setText("");

        // Tampilkan pesan sukses
        JOptionPane.showMessageDialog(null, "Data Anda berhasil diperbarui.");
        
        // Refresh tabel untuk menampilkan data yang baru diperbarui
        tampil_data();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Koneksi ke database gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
    try {
        // Mendapatkan koneksi ke database
        java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();
        
        // Query SQL untuk menghapus data dengan parameter
        String sql = "DELETE FROM subberanda_tagihan WHERE id_number = ?";
        
        // Menggunakan PreparedStatement untuk mengisi parameter
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txt_idnum.getText());
        
        // Menjalankan query
        int rowsAffected = pst.executeUpdate();
        
        // Memeriksa apakah ada baris yang terpengaruh (dihapus)
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            
            // Memanggil method tampil_data untuk merefresh tabel
            tampil_data();
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    } catch (SQLException e) {
        // Menampilkan pesan kesalahan
        JOptionPane.showMessageDialog(null, "Proses Penghapusan Gagal: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Beranda().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try {
    java.sql.Connection conn=(java.sql.Connection)com.mycompany.damdes.DAMDES.connect();
    String sql = "Select * from subberanda_tagihan where id_number='"+txt_search.getText()+"' or no_rumah='"+txt_search.getText()+"'";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rs = pst.executeQuery(sql);
    if (rs.next()){
        txt_idnum.setText(rs.getString(1));
        txt_norumah1.setText(rs.getString(2));
        txt_kodebyr.setText(rs.getString(3));
        txt_bulan.setText(rs.getString(4));
        txt_tanggal.setText(rs.getString(4));
        txt_tagihan.setText(rs.getString(5));
        JOptionPane.showMessageDialog(null,"Data Tagihan : "
        + txt_search.getText() + " Ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
    }
} catch (Exception e){}
txt_search.requestFocus();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    // TODO add your handling code here:
//    this.dispose();

    String id_number = txt_idnum.getText();
    String no_rumah = txt_norumah1.getText();
    String kode_bayar = txt_kodebyr.getText();
    String bulan = txt_bulan.getText();
    String tanggal = txt_tanggal.getText();
    String jenis_tagihan = txt_tagihan.getText();

    // Periksa apakah ada input yang kosong
    if (id_number.isEmpty() || no_rumah.isEmpty() || kode_bayar.isEmpty() || bulan.isEmpty() || tanggal.isEmpty() || jenis_tagihan.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Lengkapi Data");
        return;
    }

    // Buat query SQL dengan parameter
    String sqlquery = "INSERT INTO subberanda_tagihan (id_number, no_rumah, kode_bayar, bulan, tanggal, jenis_tagihan) VALUES (?, ?, ?, ?, ?, ?)";

    try (java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();
         java.sql.PreparedStatement pst = conn.prepareStatement(sqlquery)) {
        
        // Set parameter dalam PreparedStatement
        pst.setString(1, id_number);
        pst.setString(2, no_rumah);
        pst.setString(3, kode_bayar);
        pst.setString(4, bulan);
        pst.setString(5, tanggal);
        pst.setString(6, jenis_tagihan);

        // Eksekusi query
        pst.executeUpdate();

        // Reset teks input setelah berhasil
        txt_idnum.setText("");
        txt_norumah1.setText("");
        txt_kodebyr.setText("");
        txt_bulan.setText("");
        txt_tanggal.setText("");
        txt_tagihan.setText("");

        // Tampilkan pesan sukses
        JOptionPane.showMessageDialog(null, "Data Anda Sukses");
        tampil_data();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Koneksi ke database gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_idnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idnumActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SubBeranda_tagihan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Username;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tampil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_bulan;
    private javax.swing.JTextField txt_idnum;
    private javax.swing.JTextField txt_kodebyr;
    private javax.swing.JTextField txt_norumah1;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tagihan;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables
 
    
}
