/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.damdes;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.lang.NullPointerException;
import javax.swing.table.DefaultTableModel;
import com.mysql.cj.xdevapi.Table;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author M FAKIH IZZUL HAQ
 */
public class SubBeranda_data extends javax.swing.JFrame {
    private JPanel currentPanel;
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form SubBeranda_data
     */
    public SubBeranda_data() {
        initComponents();
        conn = DAMDES.connect();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }
    public void tampil_data() {
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("id_number");
    tabel.addColumn("no_rumah");
    tabel.addColumn("nama");
    tabel.addColumn("nomor_hp");
    tabel.addColumn("alamat");

    try {
        java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();
        String sql = "SELECT * FROM `subberanda_data`WHERE 1";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            tabel.addRow(new Object[]{
                rs.getString("id_number"),
                rs.getString("no_rumah"),
                rs.getString("nama"),
                rs.getString("nomor_hp"),
                rs.getString("alamat"),
            });
        }
        tabelpelanggan.setModel(tabel);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
    }
} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpelanggan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_idnum2 = new javax.swing.JTextField();
        txt_nmrrmh2 = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Username.setBackground(new java.awt.Color(0, 232, 232));
        Username.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Selamat Datang di Aplikasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 52), new java.awt.Color(0, 0, 204))); // NOI18N
        Username.setForeground(new java.awt.Color(0, 51, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Desa Akses Mandiri");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Pengelola Pembayaran Sampah dari BUMDes");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nomor Rumah");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID Number    ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nomor HP");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Alamat");

        simpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Tampil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Hapus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 30));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_search.setText("Cari");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel2.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        tabelpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID NUMBER", "NO RUMAH", "NAMA", "NOMOR HP", "ALAMAT"
            }
        ));
        jScrollPane1.setViewportView(tabelpelanggan);
        if (tabelpelanggan.getColumnModel().getColumnCount() > 0) {
            tabelpelanggan.getColumnModel().getColumn(0).setResizable(false);
            tabelpelanggan.getColumnModel().getColumn(1).setResizable(false);
            tabelpelanggan.getColumnModel().getColumn(2).setResizable(false);
            tabelpelanggan.getColumnModel().getColumn(3).setResizable(false);
            tabelpelanggan.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 330));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        txt_idnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idnum2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsernameLayout = new javax.swing.GroupLayout(Username);
        Username.setLayout(UsernameLayout);
        UsernameLayout.setHorizontalGroup(
            UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UsernameLayout.createSequentialGroup()
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(86, 86, 86)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_idnum2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txt_nmrrmh2)
                            .addComponent(txt_nama)
                            .addComponent(txt_nohp)
                            .addComponent(txt_alamat)))
                    .addGroup(UsernameLayout.createSequentialGroup()
                        .addComponent(simpan)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(UsernameLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsernameLayout.setVerticalGroup(
            UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernameLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsernameLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_idnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nmrrmh2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(UsernameLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Beranda().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_idnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idnum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idnum2ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
//    this.dispose();

    String id_number = txt_idnum2.getText();
    String no_rumah = txt_nmrrmh2.getText();
    String nama = txt_nama.getText();
    String nomor_hp = txt_nohp.getText();
    String alamat = txt_alamat.getText();

    // Periksa apakah ada input yang kosong
    if (id_number.isEmpty() || no_rumah.isEmpty() || nama.isEmpty() || nomor_hp.isEmpty() || alamat.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Lengkapi Data");
        return;
    }
    
    // Buat query SQL dengan parameter
    String sqlquery = "INSERT INTO subberanda_data (id_number, no_rumah, nama, nomor_hp, alamat) VALUES (?, ?, ?, ?, ?)";

    try (java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();
         java.sql.PreparedStatement pst = conn.prepareStatement(sqlquery)) {
        
        // Set parameter dalam PreparedStatement
        pst.setString(1, id_number);
        pst.setString(2, no_rumah);
        pst.setString(3, nama);
        pst.setString(4, nomor_hp);
        pst.setString(5, alamat);

        // Eksekusi query
        pst.executeUpdate();

        // Reset teks input setelah berhasil
        txt_idnum2.setText("");
        txt_nmrrmh2.setText("");
        txt_nama.setText("");
        txt_nohp.setText("");
        txt_alamat.setText("");

        // Tampilkan pesan sukses
        JOptionPane.showMessageDialog(null, "Data Anda Sukses");
        tampil_data();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Koneksi ke database gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_simpanActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
        // Mendapatkan koneksi ke database
        java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();
        
        // Query SQL untuk menghapus data dengan parameter
        String sql = "DELETE FROM subberanda_data WHERE id_number = ?";
        
        // Menggunakan PreparedStatement untuk mengisi parameter
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txt_idnum2.getText());
        
        // Menjalankan query
        int rowsAffected = pst.executeUpdate();
        
        // Memeriksa apakah ada baris yang terpengaruh (dihapus)
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            
            // Memanggil method tampil_data untuk merefresh tabel
            tampil_data();
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    } catch (SQLException e) {
        // Menampilkan pesan kesalahan
        JOptionPane.showMessageDialog(null, "Proses Penghapusan Gagal: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tampil_data();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id_number = txt_idnum2.getText();
        String no_rumah = txt_nmrrmh2.getText();
        String nama = txt_nama.getText();  // Pastikan input ini benar-benar untuk kode bayar
        String nomor_hp = txt_nohp.getText();  // Periksa apakah bulan diambil dari input nomor HP
        String alamat = txt_alamat.getText();  // Periksa apakah tanggal diambil dari input alamat

// Pastikan untuk mengambil nilai yang benar dari input pengguna
        

// Periksa apakah ada input yang kosong
if (id_number.isEmpty() || no_rumah.isEmpty() || nama.isEmpty() || nomor_hp.isEmpty() || alamat.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Masukkan semua data tagihan.");
    return;
}

// Buat query SQL untuk memperbarui data dengan parameter
String sqlquery = "UPDATE subberanda_data SET no_rumah = ?, nama = ?, nomor_hp = ?, alamat = ? WHERE id_number = ?";

try (java.sql.Connection conn = com.mycompany.damdes.DAMDES.connect();
     java.sql.PreparedStatement pst = conn.prepareStatement(sqlquery)) {

    // Set parameter dalam PreparedStatement
    pst.setString(1, no_rumah);
    pst.setString(2, nama);
    pst.setString(3, nomor_hp);
    pst.setString(4, alamat);
    pst.setString(5, id_number);  // Jangan lupa parameter untuk WHERE clause

    // Eksekusi query
    pst.executeUpdate();

    // Reset teks input setelah berhasil
    txt_idnum2.setText("");
    txt_nmrrmh2.setText("");
    txt_nama.setText("");
    txt_nohp.setText("");
    txt_alamat.setText("");

    // Tampilkan pesan sukses
    JOptionPane.showMessageDialog(null, "Data Anda berhasil diperbarui.");
    
    // Refresh tabel untuk menampilkan data yang baru diperbarui
    tampil_data();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Koneksi ke database gagal: " + e.getMessage());
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try {
    java.sql.Connection conn=(java.sql.Connection)com.mycompany.damdes.DAMDES.connect();
    String sql = "Select * from subberanda_data where id_number='"+txt_search.getText()+"' or nama='"+txt_search.getText()+"'";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rs = pst.executeQuery(sql);
    if (rs.next()){
        txt_idnum2.setText(rs.getString(1));
        txt_nmrrmh2.setText(rs.getString(2));
        txt_nama.setText(rs.getString(3));
        txt_nohp.setText(rs.getString(4));
        txt_alamat.setText(rs.getString(4));
        JOptionPane.showMessageDialog(null,"Data Transaksi Warga : "
        + txt_search.getText() + " Ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
    }
} catch (Exception e){}
txt_search.requestFocus();
    }//GEN-LAST:event_btn_searchActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubBeranda_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubBeranda_data().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Username;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelpelanggan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_idnum2;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nmrrmh2;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
